spring:
  rabbitmq:
    host: localhost
    port: 5672
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://localhost:8081/auth/realms/talci-cloud/protocol/openid-connect/token
            authorization-uri: http://localhost:8081/auth/realms/talci-cloud/protocol/openid-connect/auth
            userinfo-uri: http://localhost:8081/auth/realms/talci-cloud/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
        registration:
          spring-cloud-gateway-client:
            provider: keycloak
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/keycloak
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - TokenRelay
      routes[0]:
        id: product-service
        uri: lb://product-service
        predicates[0]: Path=/api/product
        filters:
          - RemoveRequestHeader=Cookie
      routes[1]:
        id: order-service
        uri: lb://order-service
        predicates[0]: Path=/api/order
        filters:
          - RemoveRequestHeader=Cookie
      routes[2]:
        id: inventory-service
        uri: lb://inventory-service
        predicates[0]: Path=/api/inventory
        filters:
          - RemoveRequestHeader=Cookie

eureka:
  instance:
    instance-id: ${spring.application.name}-${random.uuid}
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
