spring:
  cloud:
    stream:
      bindings:
        notificationEventSupplier:
          destination: notification-events


eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    fetch-registry: true
    register-with-eureka: true
