spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order-service?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/auth/realms/talci-cloud
  rabbitmq:
    host: localhost
    port: 5672
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    stream:
      bindings:
        notificationEventSupplier-out-0.destination: notification-events
      source: notificationEventSupplier

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
