test:
  name: test12

spring:
  rabbitmq:
    host: localhost
    port: 5672

#Discovery
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  instance:
#    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

